= pDNS
:icons: font

- [P]roxy 
- [D]omain 
- [N]ame 
- [S]erver

TIP: This is an implementation of the N26 SRE challenge.

== Justification

This project is a DNS proxy. It functions as an intermediary layer converting applications that speak DNS over TCP
on the listening interface and forwards to a DNS over TLS upstream resolver.

It is basically DNS `stunnel`.

== Synopsis

[source,bash]
----
$ ./pdns  serve --help
This command starts the DNS proxy.
	
The proxy should be made available via the defined DNS port 
(default 53) and protocols (default tcp).

Usage:
  pdns serve [flags]

Flags:
  -h, --help                     help for serve
      --listen-protocol string   The protocol on which to listen to requests (default: tcp) (default "tcp")
      --upstream-ip string       The upstream resolver to send requests to (default: 8.8.8.8) (default "8.8.8.8")

Global Flags:
      --config string      config file (default is /etc/pdns.yaml)
  -v, --log-level string   log level for the application (default is warn) (default "warn")
----

== Usage

=== Starting the daemon

The daemon can be started as follows:

[source,bash]
----
# sudo is required as the default port, 53, is below the reserved 8000 range
$ sudo ./pdns  serve
----

It is then possible to query the daemon with the `dig` utility as follows:

[source,bash]
----
$ dig @localhost andrewhowden.com +tcp
;; Connection to ::1#53(::1) for andrewhowden.com failed: connection refused.

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @localhost andrewhowden.com +tcp
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1645
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;andrewhowden.com.		IN	A

;; ANSWER SECTION:
andrewhowden.com.	299	IN	A	104.198.14.52

;; Query time: 158 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Sep 14 19:18:20 CEST 2019
;; MSG SIZE  rcvd: 61
----

== Deployment

=== Sidecar

The recommended deployment model for a proxy such as this is a "sidecar" to the application. Within Kubernetes, this
means deploying the proxy in the same pod as the application. In other orchestration tooling this means deploying the
proxy into the same network namespace as the application.

=== Service

An alternative design is to deploy the application to a specific location at which point it is discoverable.

Whether this is appropriate depends on the thread model of the infrastructure however:

- It cannot be guaranteed the local network is more trustworthy than the public
- DNS is a service discovery mechanism and this should not be discoverable via other service discovery mechanisms that
  are not cryptographically verifiable as they themselves might be poisoned.

== Security

There are various security considerations that are worth thinking about when deploying this application. Without
diving too deeply into the specifics the issues can be broken down into:

=== Privacy & Integrity of responses

The value of DNS over TLS is that any intermediaries between the application and the upstream resolver cannot inject
malformed or incorrect responses back to the client before the upstream resolver can send their response. Further, that
the those intermediaries do not have visibility into the queries that the client is making and can thus do network
discovery by proxy.

The most dangerous scenario for a DNS man in the middle attack would be when a given service that does not connect over
TLS will exchange credentials with a service that is addressed by DNS. For example, given a MySQL server running on
a kubernetes cluster and connecting without TLS could be redirected to a nefarious MySQL server that will stub the
connection out just to receive the password.

This can be addressed by listening to the proxy over localhost, where it is assumed the connection is safe from being
poisoned.

=== Denial of service

The current design of the application is such that it will simply proxy the requests to an upstream server. However, 
some components of this are particularly expensive. For example, 

- TCP session negotiation
- TLS session negotiation

Because there is no reuse, limits or other safeties on these primitives it is possible that abusive clients can make a
large number of requests to the resolver and (for example) exhaust the local ephemeral port range via connections in
TIME_WAIT or simply exhaust the number of parallel processes the proxy is able to make.

This should be addressed by introducing these facets to the application over time.

=== Binary corruption or logical flaw

Though the application as implemented is simple, there is the possibility that there is some logical flaw in the
application (for example, incorrect buffer size) that allows the crafting of malformed DNS requests. These might lead
to upstream DNS failures.

This is addressed by limiting privilege required to boot the application (perhaps via `setcap` to allow low binding
ports) and limiting the amount of access any user who manages to get code execution from the application has.

== Development

=== Getting Started

The project can be easily build and tested by running:

[source,bash]
----
cd src
go build
----

That will generate the binary `./pdns` as noted in "usage".

=== Task Runner

This project makes heavy use of the drone.io docker based pipeline tooling. More can be found at the URL:

- https://drone.io/

To install drone on a local machine see:

- https://docs.drone.io/cli/install/

The following are the tasks that are supported locally:

|===
| Task                                                          | Result

| `drone exec --pipeline=lint`                                  | Static analysis tools in the project
| `drone exec --pipeline=test`                                  | Go unit tests
| `drone exec --env-file .env --pipeline=container --trusted`   | Build the container image
|===

==== nsenter: failed to unshare namespaces: Operation not permitted

To execute the `img` container builder binary locally unprivileged user namespace cloning needs to be enabled. To do 
so, execute:

[source,bash]
----
echo 1 | sudo tee /proc/sys/kernel/unprivileged_userns_clone
----

In principle this is a harmless change, however there have been issues associated with unprivileged user namespace sharing
in the past⁴

== Git Hooks

To use the git hooks that this project expects, run the following command within the project:

[source,bash]
----
$ git config core.hooksPath $(git rev-parse --show-toplevel)/bin
----

== Minimum Viable Product (MVP)

=== Application [✔]

To have this project considered "initially complete" the project is expected to be able to fulfil a local DNS request 
over TCP and proxy that request to a given DNS over TLS upstream.

[ditaa]
....
+-----------------+                   +------------------+              +---------------------+
|                 |                   |                  |              |                     |
|  Client App     +-----DNS / TCP-----+        pDNS      +--DNS / TLS---+    CloudFlare       |
|                 |                   |                  |              |                     |
+-----------------+                   +------------------+              +---------------------+
....

=== Dockerfile [✔]

The application should be packed into a Dockerfile

=== Documentation [✔]

See this README

== Roadmap

Recommended

- [✔] The abilility to handle multiple, parallel requests
- [✔] A UDP listener

Additional

- [✔] Configurable application parameters (upstream nameserver, listen port, listen host)

Unfinished

- [x] Man pages for binary, configuration
- [×] Monitoring for the requests going through the proxy
- [×] A caching layer for the DNS responses
- [×] Multiple upstream protocols (DNS over TLS, DNS over HTTPS, DNS over TCP/UDP)

== Design

CAUTION: The following design is only the broad strokes of the project. More specific design choices associated
         with given packages, tooling or other minutiae are part of the commit log. These are visible by running
	    `git log path/to/file`

=== Architecture

The requirements of this project are to provde a "DNS over TCP to DNS over UDP proxy".

Because the DNS over TLS implementation is broadly the same as the DNS over TCP implementation, this project elects
just to create the TLS tunnel and forward the response directly to the DNS upstream, then copying the response back
to the client.

This has some advantages in that:

- It is extremely simple, being essentially a dumb forwarder
- The implementation of DNS is left to the upstream providers, and there are less opportunities for DNS bugs to slip in

However, some disadvantages in that:

- There is no ability to cache responses
- There is no visibility into what responses are being forwarded

Thus, while this technically fits requirements the project is probably not suitable for production workloads. For
production, there is the excellent CoreDNS project:

  - https://github.com/coredns/coredns/tree/master/plugin/forward

=== Project Layout

This project follows the pattern of an "all aspects of a service in one place" type design. This has worked well in
the past with cross functional teams and a high level of service ownership. See the following link for details:

- https://l.littleman.co/2V6F6ns

=== Language Choice: Go

The project requirements were open to any given language but the langauge chosen for this project was Go. This is not
the authors most familiar language, however Go has a number of characteristics that make it uniquely suitable for a
task such as this:

- Simple deployment model being a statically compiled binary
- Excellent networking libraries
- A concurrency model that should allow parallelizing requests easily
- A (relatively) small memory and compute overhead for the daemon

=== Dockerfile: Multistage, scratch

The dockerfile is a "two stage". 

==== Stage 0

Stage 0 is a Debian Buster image that:

- Contains a set of certificate authorities that are trusted by the Debian maintainers
- Contains the go runtime

The binary is compiled within this image statically

==== Stage 1

Stage 1 is "scratch" or empty image into which the certificates and the binary are copied.

Such an image has some interesting benefits:

- It is small and can be shipped across the network quickly
- There is almost no attack surface in shared libraries that might be consumed by the go binary or in processes that
  could be executed in the case there was a remote code execution.

Practically the filesystem layout looks like:

[source,bash]
----
.
├── pdns
├── etc
│   └── ssl
│       └── certs
│           ├── 02265526.0 -> Entrust_Root_Certification_Authority_-_G2.pem
│           ├── 03179a64.0 -> Staat_der_Nederlanden_EV_Root_CA.pem
│           ├── 062cdee6.0 -> GlobalSign_Root_CA_-_R3.pem
... (and so on)
----

=== CI/CD: Drone

Projects tend to benefit an extraordinarily large amount by shifting conversations associated with code style, test
coverage, linting and other project quality controls to a service that renders a binary "yes/no" decision. Further,
the development team will buy into the findings of this service much more if they are responsible for building and
understanding that service.

Further, that same service can be used to propagate changes into production based on particular version control events,
time based events or other tooling.

The "drone.io" CI/CD service is a minimal, docker based implementation of CI that allows writing very flexible and
reasonably complex pipelines but does not reinvent primitives beyond what it needs to (for example, authentication).

It has the tremendous advantage for this project that it can be executed locally, without any upstream server. This
allows it to be integrated in with git hooks, as well as some demonstration of how a conceptual CI pipeline would
look like.

== Review

The reviewers of this project are encouraged to review the git histories for a more detailed discussion as to how
a given design decision was made. The project has been recorded such that it should be possible to see the
evolution of a project by running:

[source,bash]
----
git log --reverse --patch
----

== References

1. CloudFlare, "DNS over TLS", https://developers.cloudflare.com/1.1.1.1/dns-over-tls/, Accessed Sep-2019.
2. P. Mockapetris, "Domain Names - Implementation and Specification", https://tools.ietf.org/html/rfc1035#section-4.2.2, Accessed Sep-2019
3. Wikpedia, "DNS over TLS", https://en.wikipedia.org/wiki/DNS_over_TLS, Accessed Sep-2019
4. Forest, "What does enabling unpriviged userns clone do", https://security.stackexchange.com/a/209533, Accessed Sep-2019
